Change the peer-dependency React
SeanMcP/a11y-react-emoji pull request #22
Opened 2020-10-13 02:10 UTC by arturparkhisenko

Changelog:
- Changed the peer-dependency for the `react`, checked the support for it here https://semver.npmjs.com/

2020-10-19 12:54 UTC, SeanMcP reviewed
Looks good!

2020-10-19 13:44 UTC, SeanMcP requested changes
Sorry, I'm going to take back this acceptance for small request. Can you add a line to the `CHANGELOG.md` under updated for this? That way people can point to the release when this changed.

2020-10-20 02:50 UTC, arturparkhisenko commented
@SeanMcP Changed it. And it was required to force-push after rebase because the branch was created before the previous PR with the changelog was merged.

2020-10-20 16:56 UTC, SeanMcP requested changes
Updated the wording a little bit. @arturparkhisenko does that look good?

2020-10-20 16:56 UTC, SeanMcP commented on CHANGELOG.md
> +- Changed peer-dependencies for React to include versions higher than 16
```suggestion
- Changed peer-dependencies for React to include versions greater than or equal to 16
```

2020-10-22 01:36 UTC, SeanMcP approved these changes
Looks good!

2021-03-15 23:18 UTC, merged